import type {
  DemoAgent,
  DemoKnowledgeDoc,
  DemoMetric,
  DemoProject,
  DemoReport,
  DemoWorkflowRun,
  DemoWorkflowStep,
} from "@/types/demo";

export const DEMO_PROJECTS: readonly DemoProject[] = [
  {
    id: "proj-rockhill-01",
    name: "RockHill 露天台阶爆破",
    site: "陕西 · 露天矿一期",
    status: "running",
    risk: "low",
    updatedAt: "2026-07-03T18:24:00+08:00",
    scenario: "standard",
    summary: "标准台阶条件、参数完整，Workflow 已推进到方案评分。",
    progress: 0.62,
  },
  {
    id: "proj-riverbank-02",
    name: "RiverBank 隧道爆破",
    site: "四川 · 引水隧洞 K12+450",
    status: "waiting",
    risk: "medium",
    updatedAt: "2026-07-03T17:51:00+08:00",
    scenario: "complex",
    summary: "存在炮孔含水与近距离保护对象，触发多方案对比。",
    progress: 0.48,
  },
  {
    id: "proj-urbancut-03",
    name: "UrbanCut 城市基坑爆破",
    site: "广东 · 城际铁路基坑",
    status: "blocked",
    risk: "high",
    updatedAt: "2026-07-03T16:08:00+08:00",
    scenario: "high-risk",
    summary: "缺少年允许峰值振速输入，Safety Reviewer 已阻断。",
    progress: 0.21,
  },
] as const;

export const DEMO_AGENTS: readonly DemoAgent[] = [
  {
    id: "supervisor",
    name: "Supervisor Agent",
    role: "任务编排",
    description: "理解用户目标、选择 Workflow，分配 Agent 与控制步骤。",
    mode: "thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["select_workflow", "delegate_task"],
    version: "v0.3.0",
  },
  {
    id: "normalizer",
    name: "Input Normalizer",
    role: "参数标准化",
    description: "解析自然语言与表单输入，输出标准参数对象。",
    mode: "non-thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["normalize_engineering_parameters"],
    version: "v0.2.1",
  },
  {
    id: "retriever",
    name: "Knowledge Retriever",
    role: "知识检索",
    description: "构造检索查询、返回知识片段与引用。",
    mode: "non-thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["search_knowledge"],
    version: "v0.2.4",
  },
  {
    id: "planner",
    name: "Parameter Planner",
    role: "参数规划",
    description: "根据标准化输入与知识依据进行参数预测与规划。",
    mode: "thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["plan_parameters", "analyze_parameter_sensitivity"],
    version: "v0.4.0",
  },
  {
    id: "generator",
    name: "Scheme Generator",
    role: "方案生成",
    description: "基于规划结果生成推荐、备选与风险方案。",
    mode: "thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["generate_schemes", "compare_schemes"],
    version: "v0.3.2",
  },
  {
    id: "evaluator",
    name: "Evaluation Agent",
    role: "方案评分",
    description: "调用确定性评分工具输出多指标评价。",
    mode: "non-thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["calculate_scheme_score"],
    version: "v0.1.7",
  },
  {
    id: "safety",
    name: "Safety Reviewer",
    role: "安全复核",
    description: "检查约束冲突、标记高风险并阻断。",
    mode: "thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["run_rule_check", "request_human_approval"],
    version: "v0.2.9",
  },
  {
    id: "report",
    name: "Report Agent",
    role: "报告生成",
    description: "汇总最终方案并生成结构化报告，保留引用与人工复核。",
    mode: "thinking",
    status: "idle",
    model: "deepseek-v4-pro",
    tools: ["build_report_outline"],
    version: "v0.2.0",
  },
] as const;

export const DEMO_WORKFLOW_STEPS: readonly DemoWorkflowStep[] = [
  {
    id: "validate_input",
    label: "validate_input",
    description: "校验用户输入并初始化 Run。",
    agentId: "supervisor",
    status: "succeeded",
    requiresApproval: false,
  },
  {
    id: "normalize_parameters",
    label: "normalize_parameters",
    description: "将原始输入转换为标准参数对象。",
    agentId: "normalizer",
    status: "succeeded",
    requiresApproval: false,
  },
  {
    id: "retrieve_knowledge",
    label: "retrieve_knowledge",
    description: "检索工程条件相关的知识片段与规范。",
    agentId: "retriever",
    status: "succeeded",
    requiresApproval: false,
  },
  {
    id: "run_rule_precheck",
    label: "run_rule_precheck",
    description: "执行确定性工程规则检查。",
    agentId: "safety",
    status: "running",
    requiresApproval: false,
  },
  {
    id: "plan_parameters",
    label: "plan_parameters",
    description: "进行参数预测与规划。",
    agentId: "planner",
    status: "pending",
    requiresApproval: false,
  },
  {
    id: "generate_schemes",
    label: "generate_schemes",
    description: "生成推荐、备选与风险方案。",
    agentId: "generator",
    status: "pending",
    requiresApproval: false,
  },
  {
    id: "calculate_scores",
    label: "calculate_scores",
    description: "调用评分工具输出多指标评价。",
    agentId: "evaluator",
    status: "pending",
    requiresApproval: false,
  },
  {
    id: "review_safety",
    label: "review_safety",
    description: "Safety Reviewer 复核，必要时阻断。",
    agentId: "safety",
    status: "pending",
    requiresApproval: false,
  },
  {
    id: "human_approval",
    label: "human_approval",
    description: "等待人工确认。",
    agentId: "supervisor",
    status: "pending",
    requiresApproval: true,
  },
  {
    id: "generate_report",
    label: "generate_report",
    description: "生成结构化报告。",
    agentId: "report",
    status: "pending",
    requiresApproval: false,
  },
] as const;

export const DEMO_WORKFLOW_RUNS: readonly DemoWorkflowRun[] = [
  {
    id: "run-rockhill-01",
    projectId: "proj-rockhill-01",
    status: "running",
    startedAt: "2026-07-03T17:42:00+08:00",
    durationMs: 186_000,
    steps: DEMO_WORKFLOW_STEPS,
  },
] as const;

export const DEMO_KNOWLEDGE_DOCS: readonly DemoKnowledgeDoc[] = [
  {
    id: "doc-001",
    title: "爆破安全规程（GB 6722-2014）摘要",
    category: "规范",
    page: 12,
    excerpt: "露天深孔台阶爆破应按设计孔网参数、装药结构、最大单响药量进行控制。",
  },
  {
    id: "doc-002",
    title: "乳化炸药性能与适用场景",
    category: "材料",
    excerpt: "抗水性优于铵油炸药，适用于含水炮孔；建议临界直径不小于 25mm。",
  },
  {
    id: "doc-003",
    title: "城镇周边控制爆破案例库",
    category: "案例",
    page: 47,
    excerpt: "针对学校、居民区附近必须按允许振速 v=1.0 cm/s 进行试爆校核。",
  },
  {
    id: "doc-004",
    title: "节理裂隙岩体爆破参数建议",
    category: "教材",
    excerpt: "节理发育岩体建议孔距系数取 1.0–1.2，并加密堵塞长度。",
  },
] as const;

export const DEMO_REPORTS: readonly DemoReport[] = [
  {
    id: "rep-rockhill-final",
    projectId: "proj-rockhill-01",
    title: "RockHill 露天台阶爆破 · 参数规划报告（草稿）",
    status: "draft",
    updatedAt: "2026-07-03T17:01:00+08:00",
    size: "24 页",
  },
  {
    id: "rep-riverbank-final",
    projectId: "proj-riverbank-02",
    title: "RiverBank 隧道爆破 · 方案对比报告（待复核）",
    status: "pending-review",
    updatedAt: "2026-07-03T16:18:00+08:00",
    size: "31 页",
  },
  {
    id: "rep-archive-2025",
    projectId: "proj-archive-2025",
    title: "2025 年度爆破方案归档索引",
    status: "archived",
    updatedAt: "2026-01-12T10:42:00+08:00",
    size: "12 页",
  },
] as const;

export const DEMO_METRICS: readonly DemoMetric[] = [
  {
    key: "active-projects",
    label: "进行中项目",
    value: "3",
    delta: 0.12,
    hint: "本月新增 1 个复杂约束项目",
    tone: "accent",
  },
  {
    key: "running-agents",
    label: "在线 Agent",
    value: "8",
    delta: 0,
    hint: "Agent 池全部就绪",
    tone: "primary",
  },
  {
    key: "open-risks",
    label: "待处理风险",
    value: "1",
    delta: -0.5,
    hint: "UrbanCut 已触发 Safety Reviewer",
    tone: "warning",
  },
  {
    key: "knowledge-citations",
    label: "本周知识引用",
    value: "142",
    delta: 0.08,
    hint: "命中率 86%",
    tone: "success",
  },
] as const;